#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:10.15.3

pipelines:
  branches:
    master:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm run generate
              - cd dist
              - pipe: atlassian/aws-s3-deploy:0.4.4
                variables:
                  AWS_ACCESS_KEY_ID: 'AKIA2OUEFDQZTIHBD7DJ'
                  AWS_SECRET_ACCESS_KEY: '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'
                  AWS_DEFAULT_REGION: 'us-west-1'
                  S3_BUCKET: 'yapoey.com'
                  LOCAL_PATH: $(pwd)
